apiVersion: v1
kind: Service
metadata:
  name: lms-{{.Values.global.deploymentName}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.global.services.lms.port}}
  selector:
    app: lms-{{.Values.global.deploymentName}}
