apiVersion: v1
kind: Service
metadata:
  name: idps-{{.Values.global.deploymentName}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.global.services.idps.port}}
  selector:
    app: idps-{{.Values.global.deploymentName}}
