# This file overrides settings from the 'root' values.yaml just beside this file, for the dev environment
# It is intended to be used in the following way:
# helm template -f values.yaml -f <thisfile> mychart .
# so that it may override the settings from values.yaml (keep the order of the -f args for this to work)

global:
  environment: "dev"

  database:
    server: "webmotion-dev-db-postgresql.dev-database"
    port: 5432
    database: "devfitmotion"
