apiVersion: v1
kind: Service
metadata:
  name: wcms-{{.Values.global.deploymentName}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.global.services.wcms.port}}
  selector:
    app: wcms-{{.Values.global.deploymentName}}
