apiVersion: v1
kind: Service
metadata:
  name: cis-{{.Values.global.deploymentName}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.global.services.cis.port}}
  selector:
    app: cis-{{.Values.global.deploymentName}}
