apiVersion: v1
kind: Service
metadata:
  name: ams-{{.Values.global.deploymentName}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.global.services.ams.port}}
  selector:
    app: ams-{{.Values.global.deploymentName}}
