apiVersion: v1
kind: Service
metadata:
  name: pms-{{.Values.global.deploymentName}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.global.services.pms.port}}
  selector:
    app: pms-{{.Values.global.deploymentName}}
