apiVersion: v1
kind: Service
metadata:
  name: gms-{{.Values.global.deploymentName}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.global.services.gms.port}}
  selector:
    app: gms-{{.Values.global.deploymentName}}
